### ISSUE TITLE
ALAN V0

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#11]
L'utilisation du terme IRL oblige le lecteur  a ouvrir le lien pour comprendre la phrase. Est ce qu'il ne faudrait pas le remplacer par "vrai vie"

**Comment by LeonLenclos** [comment]
Contre l'idee supprimer IRL car je trouve ça fun.
par contre on peut remplacer le lien par une parenthèse ?

Quand meme c'est drole qu'il y ait un article wikipedia pour "vraie vie"

**Comment by fabturing** [comment]
J'ai fait une modif en mettant dan la parenthèse le lien vers vraie vie, ca vous va?

**Comment by BertrandLenclos** [comment]
Ok pour moi comme ça. C'est une conversation qu'on a déjà eu avec Léon, mais moi, pour ma navigation personnelle, je préfère quand un lien ouvre un autre onglet. Ca me permet de continuer le fil de ma lecture et de voir l'anotation ou le ref à portée de main. Mais il semblerait que ce ne soit pas correct vis à vis des lecteurs. Donc si une nouvelle page doit se substituer au corpus, je pense qu'il vaut mieux que les gens ne soit pas obligé de quitter pour comprendre. C'est pour cela que je faisait cette remarque.

**Comment by LeonLenclos** [comment]
ok. du coup je crois avoir compris :

>    Un lien dans un texte doit apporter une information supplementaire, pas une information necessaire a la conmpréhension du texte

je profite de l'occasion pour ouvrir un fichier CONTRIBUTING.md qui est un fichier standard de Github (comme README) qui sers à définir les règles de contribution.
Et je met cette "règle" dedans

**Comment by fabturing** [comment]
Est ce que vous etes d'accord pour juste dire qu'il s'appelle Alan, sans insister sur le fait que c'est un hommage à turing?

**Comment by LeonLenclos** [comment]
Oui c'est vrai c'est un peu lourd car facile à deviner et pas absolument necessaire non plus de le savoir

**Comment by BertrandLenclos** [comment]
OK

**Comment by LeonLenclos** [comment]
c'est fait. Je ferme l'issue
