### ISSUE TITLE
LES IMAGES

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#12]
Ou est ce qu'on stocke les images ?

**Comment by BertrandLenclos** [comment]
Et comment on les intègre

**Comment by LeonLenclos** [comment]
j'ai créé un dossier ressources/
j'ai mis un exemple dans son readme de la syntaxe pour integrer une image

**Comment by fabturing** [comment]
Il serait bon d'intégrer un dessin à la déf de machine de turing d'ailleurs, quant tu aura le temps

**Comment by BertrandLenclos** [comment]
Un dessin aussi pour les réseaux de neurones ?

**Comment by BertrandLenclos** [comment]
Il me semble que le dossier dans l'état actuel est très technique/théorique. C'est très bien mais ça peut faire un peu peur et on peut nous reprocher de ne pas assez aborder l'aspect artistique du projet. C'est de ce côté la qu'il faut qu'on travaille maintenant. 
Des pistes : dessins, bout de dialogue avec Alan, images, ... des idées ? Qu'en pensez vous ?

**Comment by fabturing** [comment]
Je suis d'accord

**Comment by BertrandLenclos** [comment]
J'adore les nouveaux dessins

**Comment by fabturing** [comment]
Le deuxième dessin d'Alan est juste génial
