### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#14]
Est ce qu'on peut considérer que issue est un espace pour parler de choses et d'autres au sujet de TT

**Comment by LeonLenclos** [comment]
c'est certainement une bonne idée.

Je pense qu'il ne faut pas hésiter à fermer les issues qui correspondent à des problèmes réglés. Pour ne pas etre noyé sous des vieux trucs. La philosophie de base c'est quand meme, on ouvre une issue car il y a un truc a regler, on regle le probleme et on ferme l'issue.

Après on peut uttiliser ça pour autre chose que des problemes bien sur. C'est comme des mails mais rangés par discussions et archivés pas loin des textes. Donc cool pour parler du spectacle

**Comment by BertrandLenclos** [comment]
Du coup, pour éviter un engorgement de mes mails est ce qu'on peut arrêter les noifications sur mes mail perso?

**Comment by LeonLenclos** [comment]
oui bien sur. regarde les reglages de ton compte chapitre "Notifications"

**Comment by BertrandLenclos** [comment]
Je propose qu'on convienne d'un code pour fermer un issue, c'est quand les 2 autres ont liké :+1:
