### ISSUE TITLE
Le site est en ligne

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#15]
à cette adresse :
[turing-test.cienokill.fr](http://turing-test.cienokill.fr)

vos retours sont les bienvenus :)

**Comment by BertrandLenclos** [comment]
C'est de la balle

**Comment by BertrandLenclos** [comment]
Pour le lien du site de la Cie vers le corpus, as tu ne idée ?
Je pense qu'il faudrait aussi mettre le dossier V1 en ligne au même niveau que les autres spectacles.

**Comment by amparin** [comment]
Fenomenal !!!

**Comment by amparin** [comment]
mettre le lien du site de la cie au site TT. car le site TT est vachement plus agréable que le GIT

**Comment by BertrandLenclos** [comment]
Je changerais l'ordre sur la page d'accueil : 1) CONF / 2)ENVOL / 3) TT
J'ai essayé mais je comprends pas.

**Comment by fabturing** [comment]
Comment ce passe le mien du github vers le site, la mise à jour est automatique ?

**Comment by LeonLenclos** [comment]
Oui c'est un service de github qui s'appelle GitHub Pages.

**Comment by fabturing** [comment]
Génial ! on ferme cet issue ?

**Comment by LeonLenclos** [comment]
oui je ferme
@BertrandLenclos j'ai changé l'ordre des spectacles dans le site

**Comment by BertrandLenclos** [comment]
Avant de fermer je voudrais dire un truc, le lien [ici](http://turing-test.cienokill.fr/textes/) est pas assez clair. Il faut le rendre plus évident.

**Comment by BertrandLenclos** [comment]
Le mec chiant....

**Comment by LeonLenclos** [comment]
Ce lien n'est pas assez clair ou les liens en général ne sont pas assez visibles ?

(Garder en tete que le visiteur peut toujours cliquer sur "voir le sommaire")

-----------------------------------------------------------------------------------------------------

Ce serai bien d'ouvrir une nouvelle issue dans ces cas là plutot que de réouvrir une issue fermée. On a clairement pas besoin de ce qui avait été dit au-dessus pour discuter de ça.

**Comment by BertrandLenclos** [comment]
Ok je ferme. C'était aussi pour tester la ré-ouverture d'issue fermé, désolé.
