### ISSUE TITLE
104

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#16]
Léon, tu connais ce lieu ? C'est pour nous non ?
http://www.104.fr/

**Comment by LeonLenclos** [comment]
ahah tu entendais le gars sur france culture ?
Oui je connais personne là bas mais le lieu est connu a paris.

**Comment by BertrandLenclos** [comment]
oui, on regarde avec Amparo si il y a moyen de postuler

**Comment by fabturing** [comment]
J'ai été voir un spectacle là-bas, le lieu a l'air ultra cool
