### ISSUE TITLE
Compte à rebour et dead line

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#17]
-  [x] évaluation des besoins en résidence
-  [x] candidatures résidences fixer dates (104, IRIT, MJC Rodez, Grainerie, Mixart)
-  [x] évaluation des besoins technologiques (IRIT et autres)
-  [x] préparation résidence janvier
-  [x] Les partenaires de la créations
-  [ ] DRAC et autres sub (ARTCENA, DICREAM)
-  [ ] informations concernant les prévisions de cachets
-  [ ] finalisation corpus et site

**Comment by fabturing** [comment]
pas de soucis, je m'occupe d'antidote

**Comment by fabturing** [comment]
Je valide tout, j'ai mis dans les discussions les qques points qui me génaient encore mais dans l'ensemble je trouve que c'est du lourd. Je vais juste rajouter quelques sources et une capture d'écran de Pure Data demain

**Comment by LeonLenclos** [comment]
Trois nouveaux textes
[Méthode de travail](https://github.com/LeonLenclos/turing-test/blob/master/textes/methode-de-travail.md)
[Interactions](https://github.com/LeonLenclos/turing-test/blob/master/textes/interactions.md)
[Des machines qui parlent](https://github.com/LeonLenclos/turing-test/blob/master/textes/des-machines-qui-parlent.md)

Si vous trouvez qu'ils ne sont pas assez aboutits on n'est pas obligés de les ajouter tout de suite au sommaire.

J'ai aussi un peu élargit [mon texte sur ognon](https://github.com/LeonLenclos/turing-test/blob/master/textes/les-outils.md#l%C3%A9on-et-ognon) comme vous me l'avez demandé

**Comment by BertrandLenclos** [comment]
Un nouveau texte
[Besoins technologiques](https://github.com/LeonLenclos/turing-test/blob/master/textes/besoins-technologiques.md)

**Comment by LeonLenclos** [comment]
... ya que chez moi que la liste est devenue un copier-coller de l'ordre du jour ??
comment je fais pour travailler !!! 😨 🆘

**Comment by LeonLenclos** [comment]
non serieux je sais plus ce que je devais faire.
j'ai fais : 
- regler probleme images coupées
- ajouter images fabien
- retoucher intro chatbot
- corriger image experts drac
- bouton accueil

je vais devoir partir. J'espère que je n'ai rein oublié d'important. Sinon je suis de retour vers minuit 30

**Comment by BertrandLenclos** [comment]
Y a eu un putain de mauvais plan là....
Je suis vert.

**Comment by fabturing** [comment]
euh non moi aussi

**Comment by BertrandLenclos** [comment]
Je crois que c'est bon, je ré-active le lien sur cienokill

**Comment by fabturing** [comment]
Youpi !!!!!!!!!!!!!
Merci Virginie !

**Comment by BertrandLenclos** [comment]
leon il reste l'image sur turing-test.cienokill
et le marque page.

Bravo à tous, je vais me coucher parce que demain levé 5h30 cause RV à Rodez et chutte de neige prévues... d'où train à l'aube
