### ISSUE TITLE
Collaboration Irit

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#19]
Dites moi les principaux points à aborder ici pour la collaboration avec l'irit pour le chatbot

**Comment by amparin** [comment]
Hola Fabien, je pense qu'il va te dire aussi quels sont les axes de recherche qui l'intéressent, pour une collaboration l'ideal c'est qu'il trouve son compte

**Comment by amparin** [comment]
Je pense que ce qu'il peut faire pour nous dans l'immédiat c'est une lettre de soutien au projet sans préciser les actions et dans l'optique d'un partenariat, ça sera super chouette de l'avoir pour le dossier de la DRAC

**Comment by BertrandLenclos** [comment]
Je vais écrire le texte besoins technologiques ce matin et ça permettra de mettre en forme notre demande vis à vis du labo.

**Comment by BertrandLenclos** [comment]
C'est en ligne 
[Besoins technologiques](https://github.com/LeonLenclos/turing-test/blob/master/textes/besoins-technologiques.md)

**Comment by BertrandLenclos** [comment]
Alan
---------
Alan est un agent conversationnel qui échange sur scène avec les comédiens pendant le spectacle. En dehors de la scène, il est accessible au public via le site de la compagnie. Ses domaines de compétence : L'intelligence artificielle, la conscience de soi, le spectacle vivant.

Besoin logiciel :
-  Un logiciel de reconnaissance vocale.
-  Un logiciel de Chatbot. (question/réponse, apprentissage, etc…)
-  Un logiciel de synthèse vocale
-  Une base de données

Besoin matériel :
-  Un ordinateur dédié.
-  Un écran.
-  Un micro + preampli + carte son.
-  Un ampli + haut parleur.

Particularités : 
-  Il reconnait la voix de celui des trois comédiens qui lui parle.
-  Il est opérationnel en ligne et hors ligne quand le spectacle est joué sans connexion internet.
-  Son interface est suffisamment accessible pour permettre aux trois auteurs de l'administrer (apprentissage, mise à jour de la libraire, censure, etc…).

Hypothèse d'extention :
-  Alan peut aussi faire de la reconnaissance visuelle.
-  Alan est équipé d'une caméra.
-  Alan est bilingue (ou plus).

Solutions envisagées :
-  Partenariat avec L'IRIT
-  Accès aux technologies du laboratoire.
-  Une ou deux résidences d'une à deux semaines au laboratoire pour échanges, conception et formation. 
-  Définition du projet, intégration et mise au point, formation sur la maintenance et l'administration.
-  Un étudiant en Master à l'IRIT détaché sur le projet.

**Comment by BertrandLenclos** [comment]
FAbien j'ai rassemblé toutes les infos dans un mail. Surveille ta boite.

**Comment by fabturing** [comment]
J'ai vu, pas de soucis, je vous appelle ce soir ou demain

**Comment by BertrandLenclos** [comment]
Fabien tu nous feras un petit point de ta discussion avec ton oncle ?

**Comment by fabturing** [comment]
Alors il faut discuter de tous les détails lors d'un rendez-vous, a priori avant le 14 décembre.
L'accueil en résidence ne semble poser aucun problème même pour des temps longs, le soutien à la diffusion par le cnrs semble en bonne voie aussi.
Le fait qu'un stagiaire ou étudiant soit mis sur le projet dépend des effectifs, donc à voir. La mise à disposition de technologies sera possible également, à ce niveau là je crois que l'irit est une vraie mine d'or.
Pour la partie robotique ça pourrait nous ouvrir une collaboration avec le laas :
 https://www.laas.fr/public/

En gros on a pas beaucoup avancés, les détails devant êtres réglés lors d'un rendez-vous, on attends donc la réponse concernant le rendez-vous.
