### ISSUE TITLE
Machines, émotions et darwinisme modifs

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#20]
Je suggère deux petites modifs pour ce texte : 
A la fin de la section sur la théorie de l'évolution, tu liste des explications évolutionnistes à des comportements qu'on a quant on a peur. Je trouve que c'est bien que tu nuance juste après :

> D'autres comportements sont plus compliqués à expliquer : Quand j'ai peur je peut être paralysé, mes cheveux peuvent devenir blanc, je peut me faire pipi dessus, voir caca dessus, quand j'ai peur je tremble. Personne n'est parfait.

Mais je pense que ça pourrait être bien plus clair parcequ'il y a vraiment une dérive aujourd'hui je trouve qui consiste à tout mettre sur le dos de l'évolution. Des trucs du genre darwinisme social, dès fois c'est des choses pertinentes mais y a vraiment aussi des grosses conneries. C'est facile d'inventer une histoire dans sa tête dans laquelle n'importe quel comportement est un avantage. Et on sait qu'il y a bien d'autres processus d'évolutions et que tout ça est bien plus compliqué. Je propose donc 

>Mais il ne faut bien évidemment pas tout mettre sur le dos du darwinisme. L'évolution par sélection naturelle est une force qui améliore sans cesse notre adaptation à notre milieu. C'est une force puissante mais elle n'est pas la seule force qui façonne l'homme. 
>Il y a donc des comportements qui sont plus compliqués à expliquer du point de vue de l'évolution :

>Quand j'ai peur je peut être paralysé, mes cheveux peuvent devenir blanc, je peut me faire pipi dessus, voir caca dessus, quand j'ai peur je tremble. Personne n'est parfait."

La deuxième modif c'est dans la section suivante
> C'est une grande différence : l'ordinateur a ce comportement (la peur de mal s'éteindre) car ça lui permet de vivre plus longtemps

c'est trop lourd si on précise plutot 

> C'est une grande différence : l'ordinateur a ce comportement (la peur de mal s'éteindre) car ça lui permet de vivre plus longtemps et qu'il a été conçu pour vivre longtemps

**Comment by LeonLenclos** [comment]
Alors. Si j'ai bien compris tu est d'accord avec ce qui est dit mais tu trouves ça pas assez clair.

Point par point :

Un
----

Pour ta première modification, j'aurai aimé que ce soit implicite.

En vrai il y a moyen de developper beaucoup plus chaque points que je survole. Mais ce n'est pas un spectacle sur la théorie de l'évolution.

Oui c'est important de critiquer le darwinisme social mais darwin par exemple le critiquais en uttilisant sa théorie, en disant que la cooperation et l'empathie avaient étés sélectionnés.

Des théories (post-darwinistes) permettent aussi d'expliquer par la selection naturelle des comportements qui sont a première vue contre-productif. Je sais pas si tu avais lu [l'article sur la theorie du handicap](https://fr.wikipedia.org/wiki/Th%C3%A9orie_du_handicap). C'est une idée critiquable et critiquée mais que je trouve vraiment très belle. Et quitte à développer le passage "Personne n'est parfait" j'aurai aimé évoquer ça.

Du coup là j'ai l'air du mec à qui on dit "on ne peut pas tout expliquer par la selection naturelle" et qui dit "oui oui bien sûr mais en même temps, on peut tout expliquer avec la selection naturelle"

Je suis mal renseigné sur le sujet. Moi, comme je le dis dans le texte, je trouve juste ça un exercice drole et en meme temps fascinant, d'essayer d'expliquer des choses par la théorie de la selection naturelle. Si tu pense qu'il faut combattre une idée trop répendue comme quoi ça explique tout, on peut insister là dessus et ajouter ton paragraphe. Il est clair et juste, pas de soucis.

Mais le texte est déjà long et on est là dans un passage limite hors sujet, une digression interessante mais qu'il ne faut peut-être pas alourdir.

Deux
-------

Cette difference entre avoir un caractere pour repondre a un besoin et avoir un caractere parceque si on avait pas repondu au besoin on serait pas là, tout ce que j'essaye d'expliquer à ce moment là, est genre trop mega compliqué à dire simplement. Je sais pas si c'est la langue francaise ou quoi, mais je trouve qu'on dirai une idée très simple, une difference évidente entre deux concept mais qui resiste au mots.

J'avais remarqué ça quand on m'avait expliqué la difference entre le transformisme de lamark et l'evolutionnisme de darwin. J'ai l'impression que c'est un truc dans notre manière de parler de causalité.

Alors oui, ta modification rend ça plus clair. En même temps je me demande si j'amais pas un peu cette ambiguitée. Je sais pas...

D'ailleur c'est pas tant ambigue que ça. La phrase qui précède c'est quand meme "moi je suis le fruit de l'évolution, l'ordinateur lui il a été créé."

Conclusion
---------------

Les deux modifs me vont bien. J'ai essayé d'argumenter contre. Si l'argumentation ne t'as pas convaincue, fait tes modifs sans demander confirmation.
