### ISSUE TITLE
Suggestion pour continuer la lecture

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#26]
[Continuer la lecture : **Alan** >>>](http://turing-test.cienokill.fr/textes/alan.html)

     [Continuer la lecture : **Alan** >>>](alan.html)

**Comment by fabturing** [comment]
Continuer la lecture : [**Alan** >>>](alan.html)

**Comment by LeonLenclos** [comment]
les `>>>` réagissaient mal. ducoup on part sur :

---

Continuer la lecture : [Alan](http://turing-test.cienokill.fr/textes/alan.html)

    ---
 
    Continuer la lecture : [Alan](alan.html)
