### ISSUE TITLE
bebert txte alan

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#27]
Dsl bébert je crois que tu a fait une modif pendant que je corrigeais le texte d'Alan et du coup je l'ai peut etre supprimée. Vérifie

**Comment by BertrandLenclos** [comment]
J'arrête, je reprendrai quand tu as fini Antidote

**Comment by fabturing** [comment]
Et j'ai changé synthé en synthétiseur, c'est ok?
