### ISSUE TITLE
Interface improvements

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#28]
-  [x] mettre une barre verticale au dessus des liens "continuer la lecture" markdown : `---`
-  [x] mettre les liens en couleurs et peut etre pas en gras..
-  [x] amméliorer style des balises `code` ou ne pas les uttiliser ([uttilisée ici](http://turing-test.cienokill.fr/textes/interactions.html))
-  [x] améliorer la page [cienokill.fr/spectacles/turing-test/](http://cienokill.fr/spectacles/turing-test/)
-  [x] rendre le tout plus lisible en augmentant la taille de typo par exemple
-  [x] changer l'horrible bouton de la page d'accueil
-  [x] ajouter un lien pour télécharger le dossier V1 depuis le corpus. Dans les menus ?
-  [x]  est ce qu'il n'y a pas un logo concernant la licence ?
-  [x]  intégrer l'explication et le lien corpus dans V1 PDF
-  [x]  intégrer l'explication et le lien corpus dans V1 Print

**Comment by BertrandLenclos** [comment]
Je fais une suggestion. 
et si le thème (CSS, typos etc...) de http://turing-test.cienokill.fr/ était le même que celui de github.
On reste dans la même esthétique, pratique, facile, simple et clair.

**Comment by BertrandLenclos** [comment]
J'ai remonté méthode de travail en tête.
J'ai une dernière suggestion (pour ce soir....) c'est de mettre un "bouton" entre la fin de "que vais je trouver ici ?" et Sommaire pour encourager à continuer sans être obligé de se taper la lecture du sommaire. (Je dis ça parce que j'ai observé houles, qui stagnait et semblait un peu perdu au premier coup d'œil sur cette page et au final il a cliqué nimporte où, sans lire ou il allait). Ensuite celui qui veut continuer le fil clique les liens à chaque fin de page. D'ailleurs est ce qu'il ne faudrait pas ce "bouton" aussi aux fins de page. Quand je dis bouton, je sais pas ce que c'est... un truc cool. On a envie de cliquer dessus et ça veut dire : "c'est par la". Ca ferait un chemin pour ce qui veulent se laisser porter et pour les autres c'est free.

**Comment by BertrandLenclos** [comment]
![capture d ecran 2017-12-01 a 18 11 04](https://user-images.githubusercontent.com/33979100/33494293-1205255e-d6c3-11e7-983b-ff02d4291776.png)

**Comment by BertrandLenclos** [comment]
Super merci Léon.
Je n'ai pas trouvé le lien vers le dossier V1 ?

**Comment by LeonLenclos** [comment]
J'ai coché car j'ai vu qu'il était [là](http://turing-test.cienokill.fr/textes/) .

>    -  Un outil de communication pour les professionnels ou les institutions qui voudraient plus de matière que ce que le [dossier de présentation](http://cienokill.fr/wp-content/uploads/2017/11/TURING-TEST.pdf) propose.

Tu penses pas que ça suffit ?

**Comment by BertrandLenclos** [comment]
Je pense qu'il y a peu de chance que les gens identifient les liens vu qu'il faut passer la souris sur tous les mots pour tenter les trouver. C'est trop galère. Du coup celui la comme les autres passent innaperçus.
Mon avis personnel c'est que
  - il faut que les liens soient plus identifiables quand on lit.
  - peut-être le dossier V1 accessible via les menus du haut ?

**Comment by LeonLenclos** [comment]
fait
