### ISSUE TITLE
Nouveaux textes

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#29]
[Alan fait de l'humour](https://github.com/LeonLenclos/turing-test/blob/master/textes/conversation-avec-alan-1.md
)

**Comment by LeonLenclos** [comment]
[Le laboratoire](/LeonLenclos/turing-test/blob/master/textes/le-laboratoire.md)
(avis et modifications bienvenues)

**Comment by LeonLenclos** [comment]
[La machine à café](/LeonLenclos/turing-test/blob/master/textes/la-machine-a-cafe.md)

**Comment by LeonLenclos** [comment]
[Le nouveau robot](/LeonLenclos/turing-test/blob/master/textes/le-nouveau-robot.md)
J'ai écris ça, je sais pas vraiment si c'est drôle ou même si c'est bien. Mais je vous le soummet quand même.

**Comment by BertrandLenclos** [comment]
De mon point de vue je pense que tu peux intégrer les 2 premiers.
L'idée du nouveau robot est cool, mais ça mériterait d'être développé. Fabien mettrait plus de temps à comprendre le subterfuge, et ça donnerait l'occasion au public de douter lui aussi, à un moment.

**Comment by LeonLenclos** [comment]
n'hésite pas à faire des propositions directement dans le texte.

Si l'idée vous interesse comme intro il faudra de toute façon la tester vite avant de l'écrire précisement. c'était plutot une façon de vous proposer l'idée formellement. mais peut etre on peut le transformer en un texte (sans dialogues) ou l'integrer a un autre texte.
