### ISSUE TITLE
Références

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#35]
Donc quand j'étais à l'expo artiste et robots y'avais une selection de DVD a la fin. Je sais pas a quoi ça peut nous servir. Mais si au cas ou un jour on est en manque de films et series au sujet des robots ba on pourra piocher ici : 

- Eva
- Her
- Westworld
- Blade Runner
- Real Humans
- Robots
- Wall-e
- Les nouveaux heros
- Le géand de fer
- Terminator
- Le monde sur le fil
- 2001
- Tron
- Alien
- I robot
- eXistenz

**Comment by BertrandLenclos** [comment]
J'ai reproté et complété ces ref dans la biblio et je close
