### ISSUE TITLE
Proposition texte présentation

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#36]
Turing Test est une création théatrale mettant en scène des tranches de vie de trois chercheurs vacquant à leurs occupations dans un étrange laboratoire. 
Les trois experts en intelligence machine nous racontent le quotidien et les questionnements provoqués par leur volonté de créer un Homme artificiel capable de passer avec succés le test de Turing.
Les machines qu'ils construisent (robot qui souffre, robot qui a du goût, robot étonable ...) épousent les contours d'une humanité fantasmée par leurs esprits rêveurs.
Mais lorsque les chercheurs quittent le laboratoire, quand plus personne n'est là pour discuter avec Alan le robot conversationnel, le vide ne se fait pas tout à fait. Il reste les robots ainsi que les idées et les inquiétudes des chercheurs qui habitent le laboratoire et qui le remplissent de sons et d'images.

**Comment by LeonLenclos** [comment]
Ok je pense qu'il y a pas mal d'éléments interessants mais que ça fait pas un bon texte de présentation pour l'instant. Ce texte fait un bon résumé de là où on en est dans la création. Je pense qu'il est bon a placer  (peut etre apres quelques modifications) dans le git et dans un éventuel nouveau fascicule papier. Mais je pense pas que c'est ce qu'il nous faut comme texte d'accroche.

Ça décrit trop précisement le spectacle. Je trouve ça cool de lire ça maintenant car ça met les idées au clairs sur les intentions fondamentales du spectacle tel qu'il est. Mais c'est pas ça qu'il faut donner aux gens.

Aussi, au niveau du style je pense qu'il faut aller sur un truc plus simple à lire. Si ça se retrouve dans des programmes de festival/théatres et sur des sites exterieurs ça doit pouvoir être lu en diagonal ou par quelqu'un qui viens de lire 10 résumés de spectacles. Donc concretement phrases plus courtes, plus directes, groupes nominaux plus legers.

D'un ceci n'engage que moi et de deux j'ai pas de meilleure idée à proposer tout de suite. Je pense qu'il faut encore creuser un peu. On peut faire d'autres propositions sur cette issue par exemple ? 

Dites moi si je suis pas clair ou si je me fourvoie.

:kissing:
