### ISSUE TITLE
Fiche turc

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#37]
Il manque la fiche de turc dans la liste des robots !!

**Comment by LeonLenclos** [comment]
bien vu. Tu as ses photos ?

**Comment by fabturing** [comment]
Oui je viens de les redimensionner et les mettre dans le dossier ressource (turc1.JPG à turc5.JPG)

**Comment by LeonLenclos** [comment]
Du coup je met `(fiche à rédiger)` dans la liste des robots devant tous les robots qu'il manque
