### ISSUE TITLE
Retour Amparo

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/turing-test#38]
> Il y a juste un truc qui n’est pas très clair pour moi :

> Alan peut improviser des réponses en se fondant sur un apprentissage profond basé sur un corpus de répliques de films récupérées via les fichiers de sous-titres.
> 
> Si on lui dit une phrase qu’il connait (car elle fait partie de son corpus) il choisi au hasard une de ses réponses ?
> Si on lui dit une phrase qu’il ne connait pas : l’utilisateur peut lui apprendre des nouvelles réponses?
> 
> Bises
> 
> Amparo Gallur

**Comment by fabturing** [comment]
J'ai répondu rapidement par mail : 
 Alan ne se rapelle pas vraiment des phrases de son corpus, disons plutot qu'Alan voit une réplique et sa réponse comme une structure abstraite composée de mots. Pendant son apprentissage, il apprend des mots et essaie de détecter les règles qui régissent l'enchainement des mots. C'est ses règles d'enchainement des mots pour former une réponse qu'il apprend dans son corpus, pas des répliques entières.

**Comment by fabturing** [comment]
Bon je ferme l'issue du coup. Rouvrez là si vous trouvez qu'il y a des choses à rectifier
