### ISSUE TITLE
mise f6

### ISSUE THREAD

**Issue by f6lopez** [LeonLenclos/turing-test#41]
Mise f6

Sur scène :
Les leds sont elles bien réglées ?
Le fond de scène est il clean ?
La machine à fumée est elle allumée ?
Le micro établi est il en place ?
Vérifie les réglages des F1 s’il te plait
Allume Caro et vérifie le cadre de la première scène 
Va garer Caro près du frigo
Allume le récepteur de Matt
Allume l’émetteur du morpion

En régie :
La pédale est elle allumée ?
Souviens toi , Il ne faut pas que ma voix soit trop forte au départ.
Comme pour Jimmy 
Pour Echo aussi
Et Pour Klan et son délai

**Comment by LeonLenclos** [comment]
Ok ta mise a été intégrée à Alan (sur la branche `hotfix-mise`). Pour raison de sécurité on ne la met pas sur la branche `master` tout de suite. Donc pas encore accessible depuis Alan sur scène.

> Sauf necessité extrême, aucune mise à jour de robot ne devra être faite le jour d'une représentation.
(Loi n°3 de La cellule risques du GRIM)

Dès la prochaine mise à jour d'Alan, ta mise sera accessible en tapant  "mise francis", "mise f6", "mise de francis" ou  "mise de f6" avec ou sans majuscules.
