### ISSUE TITLE
à commander rapidement + à faire avant MIMA

### ISSUE THREAD

**Issue by f6lopez** [LeonLenclos/turing-test#42]
PROCHAINE COMMANDE NOKILL :
THOMANN:
8 PAR 36 F1 
https://www.thomann.de/fr/stairville_par36_pinspotset_schwarz.htm
+ 8 LAMPES GE 
https://www.thomann.de/fr/ge_4515.htm
+ 1 COLLIER 
https://www.thomann.de/fr/doughty_t21101.htm
+ 1 EMBASE POUR PIED 
https://www.thomann.de/fr/stairville_ts_1_light_adapter.htm
+ 2 DI NEUTRIK 
+ 8 XLR male et femelle 4pts pour alim led

CABLAGE MICRO DE COULEUR
micro établi 13 m
vox Alan 20 m
key Alan 20 m
Di klan 4m
mic jimmy 4 m
Écho 13m
cafetière 13 m
Tr808 10m
bssline 10m
reverb 10 m
il y a aussi la prolongation du jouet de léon que je n'ai pas calculé à voir si on récupère des cables qui ne servent pas ...

FERAILLE:
Pour les led
4 x 1,20m U ACIER 20X10MM
Pour les F1 
2 barres de 90 cm de haut

A CONSTRUIRE :
Barre led pour le dessous des tables
REFLECHIR A UN CABLAGE POUR OTTO JUSQU’A DI

AMENER BOITE MICRO Bebert à mima

**Comment by LeonLenclos** [comment]
La bonne place pour ça est le fichier `todo.md`

dans [turing-test/contenu/organisation/todo.md](https://github.com/LeonLenclos/turing-test/blob/master/contenu/organisation/todo.md) 

J'ai copié toutes les infos ci dessus. Pour éditer c'est le petit crayon (en haut à droite) puis le bouton vert (commit) pour valider.

Si jamais tu te pose des question sur le formattage (listes, titres, liens, etc.) tu peux checker [markdown](https://fr.wikipedia.org/wiki/Markdown). Mais si t'as pas que ça à faire, c'est fait pour être lisible et éditable par qq1 qui ne connait pas la syntaxe.

**Comment by BertrandLenclos** [comment]
bon c'est vieux je close
