### ISSUE TITLE
Affiche Turing Test

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#43]
Mon point de vue par rapport à la proposition d'affiche V0 de Léon 
# Le titre

- Typo qualifiée de "un peu stressante"  par Amparo et de "peu lisible et flottante" par Pascale
- validée par Fab : "J'aime beaucoup la police"
- Pour ma part je trouve intéressant l'idée d'une écriture manuscrite (mal) imitée par une machine.
on ne peut pas nier que ce soit un peu inquiétant et trouble. Est ce un défaut ? 
- De mon point de vue, il n'y a pas de problème de lisibilité

# Le sous-titre

- Drole mais en même temps déprécie notre travail en insistant sur le manque d'originalité du sujet. Ce qui en communication est plutôt déconseillé. 
- A garder en attendant de trouver mieux.

# Les logos

- remonter IRIT dans les soutiens. 
- Equilibrer Mazades et Bonnefoy
- Ajouter Vertigo dans les partenaires

# Dans l'ensemble

- Je la trouve super.
- C'est à Léon de prendre la décisioin finale concernant les points qui font débat.

**Comment by LeonLenclos** [comment]
Ok on lance un premier tirage

**Comment by BertrandLenclos** [comment]
c'est calé je close
