### ISSUE TITLE
MAJ du GitHub Turing Test

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#45]
Plusieurs MAJ sont nécessaires sur le site, je dirais même qu'un petit coup de clean s'impose.
En deux mots, mettre les fiches robots à jour, changer certains textes qui font penser que la première n'a pas eu encore lieu, etc...
Cependant, je pense que c'est bien de tout garder, juste spécifier quand c'est des hypothèses de travail qui ont été abandonnées, et ouvrir des perspectives d'évolutions quand cela se justifie.

je propose de les lister pour visualiser l'avancement.

- [x] LISTE DES ROBOTS DU LABORATOIRE

- [x] - [Alan](alan.md)
- [x] - [Otto](otto.md)
- [x] - [Foot](foot.md)
- [x] - [Echo](echo.md)
- [x] - [Lucy](lucy.md)
- [x] - [Jimi](jimi.md)
- [x] - [Klan](klan.md)
- [x] - [Core](core.md)
- [x] - [Caro](caro.md)
- [x] - [Mimi](mimi.md)
- [x] - [Toto](toto.md)
- [x] - [Turc](turc.md)
- [x] - [Dedo](dedo.md)
- [x] - [Maki](maki.md)
- [x] - [Matt](matt.md) (fiche à rédiger)
- [x] - [Lisa](lisa.md) (fiche à rédiger)
- [x] - [Dodo](dodo.md) (fiche à rédiger)

Autres idées de robots :

- [x] - [Robots marionnette](robots-marionnette.md)
- [x] - [Robot Poète](robot-poete.md)
- [x] - [Robot qui perd aux jeux](robot-qui-perd-aux-jeux.md)
- [x] - [Robot qui applaudit](robot-qui-applaudit.md)
- [x] - [Robot taciturne](robot-taciturne.md)

- [x] DES NOTES DINTENTIONS

- [x] DES TEXTES A LIRE, ETC

- [x] DES IDÉES DE SCÈNES

- [x] UNE BIBLIOGRAPHIE

- [x] L'ORGANISATION

**Comment by LeonLenclos** [comment]
ok yes.

J'en ferai un peu dans les prochains j.

**Comment by BertrandLenclos** [comment]
Hello les potos, j'ai fait une passe sur tous les textes du site. Avec Virginie on va faire une grosse passe d'orthographe et voila un site à peu prèt à jour et plutôt cool je trouve.
Dès que vous validez je ferme l'issue.

**Comment by LeonLenclos** [comment]
Bravo pour le taf !

**Comment by fabturing** [comment]
J'ADORE ! Un grand bravo, en plus d'être super bien complété la navigation sur le site est claire fluide et très agréable. Beaucoup plus de cohérence qu'avant !
