### ISSUE TITLE
Liens non opérationnels

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#46]
C'est peut être fait exprès ou a déjà fait l'objet d'une discussion, mais les liens suivants ne fonctionnent pas :
Sur le site : 
    - lien atelier
Sur le github
    - tous les liens dans les read me

Je ne sais pas comment régler ça....

**Comment by LeonLenclos** [comment]
???
Je n'arrive pas à voir de quoi tu parles. met moi les liens des pages où tu vois des liens morts.

**Comment by BertrandLenclos** [comment]
est ce qu'il ne faudrait pas que ce lien mort : http://turing-test.cienokill.fr/contenu/organisation/ateliers
pointe vers celui la : http://turing-test.cienokill.fr/dossier/ateliers.html

Concernant le GitHub,c'est ce type de liens qu'on trouve en bas de page organisation par exemple qui ne marchent pas : 
https://github.com/LeonLenclos/turing-test/blob/master/contenu/organisation/residences

**Comment by LeonLenclos** [comment]
> ce lien mort : http://turing-test.cienokill.fr/contenu/organisation/ateliers

Tu l'as trouvé ou ce lien ?

**Comment by BertrandLenclos** [comment]
tu vas sur le site du spectacle : http://turing-test.cienokill.fr/ 
dans la page d'accueil tu cliques sur organisation : http://turing-test.cienokill.fr/contenu/organisation/
dans organisation tu cliques sur atelier.

**Comment by LeonLenclos** [comment]
ok pardon.

Donc deux choses differentes : le lien **atelier** était un lien mort. Je l'ai corrigé.

Sinon les autres liens ne marchent pas sur github. Mais j'ai l'impression que c'est le prix à payer pour qu'ils marchent sur le site...

Je vois pas grand choses à faire. À part, si on veut faire du zele, mettre un petit message d'avertissement.

Pour rappel, cette syntaxe permet d'entrer du texte visible sur github mais masqué sur github-pages (sur le site)

```
<p class="github-pages-ignore">
    Si vous voyez ce texte c'est que vous êtes sur Github. Et si vous visitiez plutôt le site  : <a href="http://turing-test.cienokill.fr">turing-test.cienokill.fr</a> pour une lecture plus agréable ?
</p>
```

**Comment by BertrandLenclos** [comment]
C'est pas très grave. On peut laisser comme ça. Je close.
