### ISSUE TITLE
Déroulé du spectacle

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#47]
Hello le Grim. Les affaires reprennent. Plusieurs dates de TT en perspective.
C'est dans ce contexte que je vous propose de compléter et d'ajuster [le déroulé à jour](https://github.com/LeonLenclos/turing-test/blob/master/contenu/scenes/deroule.md) que j'ai commencé à écrire sur la base de ce dont je me souviens... Je crois que ça vaut le coup d'être précis, car ça peut constituer un bon outil de travail pour reprendre le spectacle. Une fois que vous avez fait votre passe et vérifié que tout est OK, on fait une passe d'orthographe avec Virginie et on close l'issue.

**Comment by LeonLenclos** [comment]
Ok j'ai fait une petite passe et j'ai essayé de plus découper le déroulé en partie avec (surtout pour l'acte 1) les indications d'intension de jeu pour chaque partie.

Si ce découpage n'est pas clair ou qu'il ne correspond pas à une réalité selon vous on peut revenir en arrière.

**Comment by BertrandLenclos** [comment]
pour moi le découpage fonctionne bien et est utile pour se remettre dedans.

**Comment by BertrandLenclos** [comment]
Des que Fabien valide, on close l'issue.

**Comment by fabturing** [comment]
C'est bon pour moi, j'ai juste touché quelques détails de l'acte 3. On pourrait proposer à Francis d'ajouter les mouvements de Caro ? (Caro est-elle une comédienne ? A-t-elle plutôt ça place sur une fiche technique ? Je vous le demande !)
