### ISSUE TITLE
CSS du site

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/turing-test#48]
Je ne suis pas complètement convaincu du CSS des liens dans le site TT (gras + souligné). C'est un peu too much non ?

**Comment by LeonLenclos** [comment]
juste gras alors ? ou juste souligné ?

**Comment by BertrandLenclos** [comment]
plutôt gras non ?

**Comment by LeonLenclos** [comment]
ok je vais faire ça. et qui se souligne quand on survole.

**Comment by LeonLenclos** [comment]
styles des titres. plusde difference de taille et peut etre enlever le soulignage sur les h3 +

**Comment by LeonLenclos** [comment]
@BertrandLenclos Le nouveau style te va mieux ?

**Comment by BertrandLenclos** [comment]
Yes pour moi c'est OK
