### ISSUE TITLE
éthique

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/turing-test#8]
On peut pas faire sauter cette phrase puisqu'il me semblait qu'on étés pas d'accord avec ?

>   Certains observateurs constatent un assèchement de la créativité en matière de science fiction probablement du au fait de l'accélération technologique.

**Comment by BertrandLenclos** [comment]
Oui je voulais repasser sur ce texte mais je n'ai pas eu le temps. Est ce que vous me laissez jusqu'à demain ?

**Comment by fabturing** [comment]
^^ Oui aucun souci désolé

**Comment by LeonLenclos** [comment]
j'avais pas lu ta reponse du coup j'ai fait une proposition #10 
ça peut virer si tu avait une idée. On peut aussi le réutiliser ailleur.

**Comment by BertrandLenclos** [comment]
Non très bien, je vais juste modifier le dernier paragraphe avant le merge

**Comment by BertrandLenclos** [comment]
c'est fait
